name: ci-golang-workflow
on: 
  pull_request:
    branches:
      - develop
jobs:
  check-application:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        go: ['1.14', '1.15']
        
    steps:
      - uses: actions/checkout@v2 #download new features add
      - uses: actions/setup-go@v2 #setup go enviroment
        with:
          go-version: ${{ matrix.go }}
      - run: go test
      - run: go run math.go
